Repository TweetWallFX/TweetwallFX, pull requests merged in 2018-11, with the labels that each got.

#624 Updated spotless dependency to version 3.16.0.
  gradle.properties
Labels: dependency

#626 Updated Nebula Publishing dependency to version 9.2.0.
  gradle.properties
Labels: dependency

#641 Readded test of StringNumberComparator.
  util/src/test/groovy/org/tweetwall/util/StringNumberComparatorSpec.groovy
  util/src/test/java/org/tweetwallfx/util/StringNumberComparatorTest.java
Labels: SWQA

#645 Ensure dataprovider restriction is correct during shouldSkip check
  stepengine-api/src/main/java/org/tweetwallfx/stepengine/api/StepEngine.java
Labels: bug

#652 Made SchedulaDataProvider.scheduleSlots volatile to ensure that the l…
  devoxx-cfp-stepengine/src/main/java/org/tweetwallfx/devoxx/cfp/stepengine/dataprovider/ScheduleDataProvider.java
Labels: bug

#667 Added missing service registration for FilterStepFactoryUniqueStep.
  filterchain/src/main/resources/META-INF/services/org.tweetwallfx.util.testcase.RunnableTestCase
Labels: bug

#666 Added FilterChainStepsAvailable checking that FilterSteps that are re…
  filterchain/src/main/java/org/tweetwallfx/filterchain/testcase/FilterChainStepsAvailable.java
  filterchain/src/main/resources/META-INF/services/org.tweetwallfx.util.testcase.RunnableTestCase
Labels: enhancement

#669 Corrected javadoc.
  stepengine-api/src/main/java/org/tweetwallfx/stepengine/api/config/StepEngineSettings.java
Labels: enhancement

#671 Corrected bean method.
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/filter/UserMinimumFollwerCountFilterStep.java
Labels: bug

#673 Added object to JSON conversion method to JsonDataConverter.
  util/src/main/java/org/tweetwallfx/util/JsonDataConverter.java
Labels: enhancement

#680 Remove oldest image instead of newest in case the stored exceeds the …
  stepengine-dataproviders/src/main/java/org/tweetwallfx/stepengine/dataproviders/ImageMosaicDataProvider.java
Labels: bug

#688 Using twitter handle provided by screen name.
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/filter/AcceptFromSenderFilterStep.java
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/filter/RejectFromSenderFilterStep.java
Labels: bug

#693 Implemented toString for UserMinimumFollwerCountFilterStep.Config
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/filter/UserMinimumFollwerCountFilterStep.java
Labels: enhancement

#704 Added filterstep checking images in tweets with Google Vision API.
  google-cloud/build.gradle
  google-cloud/src/main/java/org/tweetwallfx/google/GoogleLikelihood.java
  google-cloud/src/main/java/org/tweetwallfx/google/GoogleSettings.java
  google-cloud/src/main/java/org/tweetwallfx/google/vision/CloudVisionSettings.java
  google-cloud/src/main/java/org/tweetwallfx/google/vision/GoogleVisionCache.java
  google-cloud/src/main/java/org/tweetwallfx/google/vision/ImageContentAnalysis.java
  google-cloud/src/main/java/org/tweetwallfx/google/vision/ImageContentFilterStep.java
  google-cloud/src/main/resources/META-INF/services/org.tweetwallfx.config.ConfigurationConverter
  google-cloud/src/main/resources/META-INF/services/org.tweetwallfx.filterchain.FilterStep$Factory
  google-cloud/src/main/resources/tweetwallConfig.json
  gradle.properties
  settings.gradle
Labels: enhancement

#713 Re-Activated TwitterTweeterTest and added log4j2.xml.
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/Tweet.java
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/entry/EmojiTweetEntry.java
  tweet-impl-twitter4j/src/test/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterTweeterTest.java
  tweet-impl-twitter4j/src/test/resources/log4j2.xml
Labels: bug

#716 Implemented toString methods for TweetEntry subclasses.
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/entry/EmojiTweetEntry.java
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/entry/MediaTweetEntrySize.java
  tweet-impl-twitter4j/src/main/java/org/tweetwallfx/tweet/impl/twitter4j/BaseTwitterTweetEntry.java
  tweet-impl-twitter4j/src/main/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterMediaTweetEntry.java
  tweet-impl-twitter4j/src/main/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterUrlTweetEntry.java
  tweet-impl-twitter4j/src/main/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterUserMentionTweetEntry.java
Labels: enhancement

#720 Upgraded version of ehcache dependency to 3.6.2.
  gradle.properties
Labels: dependency

#721 Added getFollowers and getFriends to Tweeter.
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/Tweeter.java
  tweet-api/src/main/java/org/tweetwallfx/tweet/api/config/TwitterSettings.java
  tweet-impl-twitter4j/src/main/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterTweeter.java
  tweet-impl-twitter4j/src/test/java/org/tweetwallfx/tweet/impl/twitter4j/TwitterTweeterTest.java
Labels: enhancement
